[project]
authors = ["Silvio <silvio.traversaro@iit.it>"]
channels = ["conda-forge", "robostack-staging"]
description = "Add a short description here"
name = "turtlebotgazebo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[activation.env]
TURTLEBOT3_MODEL = "burger"

[tasks]
launch_sim = "ros2 launch turtlebot3_gazebo empty_world.launch.py"


[dependencies]
ros-humble-turtlebot3-gazebo = "*"
ros-humble-desktop = "*"
ros-humble-turtlebot3 = "*"

[feature.mutex03.dependencies]
ros2-distro-mutex = "0.3.*"

[feature.mutex05.dependencies]
ros2-distro-mutex = "0.5.*"

[feature.mutex06.dependencies]
ros2-distro-mutex = "0.6.*"

[environments]

default = ["mutex06"]
mutex06 = ["mutex06"]
mutex05 = ["mutex05"]
mutex03 = ["mutex03"]
